### ISSUE TITLE
support dark mode

### ISSUE THREAD

**Issue by drom** [wavedrom/github#5]
```html
<html data-color-mode="dark">...
```

https://gist.github.com/kaicataldo/f28b6adf941d1575afa78e647624a327

```css
:root {
  /* Light theme */
  --text-color: #333333;
  --background-color: #ffffff;
}

/* Dark theme */
[data-color-scheme='dark'] {
  --text-color: #ffffff;
  --background-color: #181b25;
}

body {
  color: var(--text-color); 
  background-color: var(--background-color);
}
```

https://livecodestream.dev/post/a-better-approach-to-dark-mode-on-your-website/
